[package]
authors = ["Daniel Solnik <dansolnik@gmail.com>"]
edition = "2018"
name = "RAFT"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"
